# -*- coding: utf-8 -*-
"""netflix_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cYFEqmSKGsgB_uov-PafJlVmn4qrmhWc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

netflix = pd.read_csv("/content/netflix_titles.csv")

netflix.head()

netflix.drop(["show_id","description"],axis=1,inplace=True)

netflix.describe()

netflix.info()

netflix.isnull().sum()

netflix = netflix.dropna(subset=['duration'])

netflix["rating"].mode()

netflix["date_added"].mode()

netflix = netflix.fillna({"director":"Unknown",
                "cast":"Unknown",
                "country":"Unknwn",
                "date_added":"January 1, 2020",
                "rating":"TV-MA"})

netflix.isnull().sum()

netflix['date_added'] = netflix['date_added'].str.strip()
netflix['date_added'] = pd.to_datetime(netflix['date_added'], errors='coerce')

netflix['year_added'] = netflix['date_added'].dt.year
netflix['month_added'] = netflix['date_added'].dt.month

netflix['duration_int'] = netflix['duration'].str.extract('(\d+)').astype(float)
netflix['duration_type'] = netflix['duration'].str.extract('([a-zA-Z]+)')

netflix.head()

netflix["country"].value_counts()

# comparison between tv sho and Movie
type_count =  netflix["type"].value_counts()

plt.bar(type_count.index,type_count,color=["skyblue","orange"],width=0.6,edgecolor="black",linewidth=1)
plt.ylabel("total shows and movies",color="black",fontsize=12,fontweight="bold")
plt.title("Comparison between Numbers of shows Movies & Tv Shows")
plt.show()

count_years = netflix["release_year"].value_counts().reset_index()
count_years.head()

plt.figure(figsize=(10,5))
plt.plot(count_years['release_year'], count_years['count'],  marker='o',color='blue')
plt.title("Netflix Titles Released Per Year", fontsize=14)
plt.xlabel("Year")
plt.ylabel("Number of Releases")
plt.grid(True)
plt.show()

netflix.isnull().sum()

top_countries = netflix[netflix['country'] != 'Unknwn']['country'].value_counts().reset_index().head(10)
top_countries
plt.barh(top_countries["country"],top_countries["count"])
plt.xlabel("Number of released",fontsize=12,fontweight="bold")
plt.ylabel("Countries",fontweight="bold",fontsize=12)
plt.title("Netflix Released Per Year (Country)", fontsize=12,fontweight="bold")
plt.show()

# Top 10 dircter released based
director = netflix["director"].value_counts().drop("Unknown").head(10).reset_index()
director
plt.barh(director["director"],director["count"],color="Green")
plt.tight_layout()
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.xlabel("Number Of Movies/Shows",fontsize = 12,fontweight="bold")
plt.ylabel("Drector Name",fontsize = 12,fontweight="bold")
plt.title("Total Movies/Shows Based On Tv & Shows",fontweight="bold")
plt.show()